table cliente
	lineageTag: 3784e178-8ca3-4f31-a5c9-0af236335e4b

	column id
		dataType: int64
		formatString: 0
		lineageTag: cb3322a5-d214-4768-a85d-65afb5389bcf
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nombre_completo
		dataType: string
		lineageTag: fa412f33-bfa1-49a8-a24e-638bfc308e64
		summarizeBy: none
		sourceColumn: nombre_completo

		annotation SummarizationSetBy = Automatic

	column correo_electronico
		dataType: string
		lineageTag: f7afbb63-8818-4f11-818f-0ffc5d782d31
		summarizeBy: none
		sourceColumn: correo_electronico

		annotation SummarizationSetBy = Automatic

	column telefono
		dataType: string
		lineageTag: 90a82292-4295-4606-a427-8d657ca9f841
		summarizeBy: none
		sourceColumn: telefono

		annotation SummarizationSetBy = Automatic

	column genero_Id
		dataType: int64
		formatString: 0
		lineageTag: ef4d809e-33bf-4dc4-b690-0d4992150036
		summarizeBy: count
		sourceColumn: genero_Id

		annotation SummarizationSetBy = Automatic

	column nacionalidad_Id
		dataType: int64
		formatString: 0
		lineageTag: cde461f2-3cea-4bbf-8c8b-d30c6cc108d8
		summarizeBy: none
		sourceColumn: nacionalidad_Id

		annotation SummarizationSetBy = Automatic

	partition cliente = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Cesia\Downloads\BD_HOTEL_INDIANA_GENERADO_200.xlsx"), null, true),
				    cliente_Sheet = Origen{[Item="cliente",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(cliente_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"nombre_completo", type text}, {"correo_electronico", type text}, {"telefono", type text}, {"genero_Id", Int64.Type}, {"nacionalidad_Id", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

