table metodo_pago
	lineageTag: 8764cb48-0981-49d3-a5eb-747c2dff14ef

	column id
		dataType: int64
		formatString: 0
		lineageTag: 7ed3ae88-062d-4a1d-bbd0-92d617c74a79
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nombre
		dataType: string
		lineageTag: 83884cd5-607e-4e00-8ae6-9cc8d27cb00b
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	partition metodo_pago = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Cesia\Downloads\BD_HOTEL_INDIANA_GENERADO_200.xlsx"), null, true),
				    metodo_pago_Sheet = Origen{[Item="metodo_pago",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(metodo_pago_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"nombre", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

