table preferencia_especial
	lineageTag: 24748974-4b00-47d4-bcff-c46de1cabc74

	column id
		dataType: int64
		formatString: 0
		lineageTag: 9b2bde80-143c-4a33-a7e9-55dcff4b40c7
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: 5c47fb15-ea5c-42b0-918a-ce3c7a6c3b9c
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	partition preferencia_especial = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Cesia\Downloads\BD_HOTEL_INDIANA_GENERADO_200.xlsx"), null, true),
				    preferencia_especial_Sheet = Origen{[Item="preferencia_especial",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(preferencia_especial_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"descripcion", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

