table tipo_servicio
	lineageTag: cace35d0-b479-48fa-aa55-cc75e19b12bc

	column id
		dataType: int64
		formatString: 0
		lineageTag: d6e5010d-ecea-49a7-a499-cc844275f725
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nombre
		dataType: string
		lineageTag: 19fe8243-4ddc-4faf-b805-71acf98e4027
		summarizeBy: none
		sourceColumn: nombre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: 877ac21a-3b14-4df3-b1d4-a48206f82a96
		summarizeBy: none
		sourceColumn: descripcion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition tipo_servicio = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Cesia\Downloads\BD_HOTEL_INDIANA_GENERADO_200.xlsx"), null, true),
				    tipo_servicio_Sheet = Origen{[Item="tipo_servicio",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(tipo_servicio_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"nombre", type text}, {"descripcion", type any}})
				in
				    #"Tipo cambiado"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

